# Generated by Django 4.0.5 on 2022-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
